/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueuesQueueNameRouteImport } from './routes/queues/$queueName'
import { Route as QueuesJobsQueueNameJobIdRouteImport } from './routes/queues/jobs.$queueName.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueNameRoute = QueuesQueueNameRouteImport.update({
  id: '/queues/$queueName',
  path: '/queues/$queueName',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesJobsQueueNameJobIdRoute =
  QueuesJobsQueueNameJobIdRouteImport.update({
    id: '/queues/jobs/$queueName/$jobId',
    path: '/queues/jobs/$queueName/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/queues/jobs/$queueName/$jobId': typeof QueuesJobsQueueNameJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/queues/jobs/$queueName/$jobId': typeof QueuesJobsQueueNameJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/queues/jobs/$queueName/$jobId': typeof QueuesJobsQueueNameJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/queues/$queueName' | '/queues/jobs/$queueName/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/queues/$queueName' | '/queues/jobs/$queueName/$jobId'
  id: '__root__' | '/' | '/queues/$queueName' | '/queues/jobs/$queueName/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueuesQueueNameRoute: typeof QueuesQueueNameRoute
  QueuesJobsQueueNameJobIdRoute: typeof QueuesJobsQueueNameJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$queueName': {
      id: '/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof QueuesQueueNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/jobs/$queueName/$jobId': {
      id: '/queues/jobs/$queueName/$jobId'
      path: '/queues/jobs/$queueName/$jobId'
      fullPath: '/queues/jobs/$queueName/$jobId'
      preLoaderRoute: typeof QueuesJobsQueueNameJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueuesQueueNameRoute: QueuesQueueNameRoute,
  QueuesJobsQueueNameJobIdRoute: QueuesJobsQueueNameJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
